spring:
  application:
    name: springcloud-service-consumer-feign
server:
  port: 8030
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8765/eureka
  instance:
    prefer-ip-address: true