server:
  port: 8765
  address: 127.0.0.1
eureka:
  instance:
    hostname: discovery
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url :
      defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka